"""add_permissions_and_super_admin

Revision ID: 9429f53cc7e9
Revises: 9eb9e2356418
Create Date: 2025-11-24 16:27:18.974082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9429f53cc7e9'
down_revision: Union[str, Sequence[str], None] = '9eb9e2356418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add permissions column to roles (nullable)
    op.add_column('roles', sa.Column('permissions', sa.Text(), nullable=True))
    
    # Add is_super_admin column to users
    # First add as nullable, then set default for existing rows, then make NOT NULL
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    
    # Set all existing users to False (not super admin)
    op.execute("UPDATE users SET is_super_admin = FALSE WHERE is_super_admin IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'is_super_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
